<?php
    $_collection = $this->getArchivedList();
    $helper = Mage::helper('inchoo_supportticket')
?>
<div class="page-title title-buttons">
    <h1>
        <?php echo $this->__('My Tickets') ?>
    </h1>
    <button type="button" title="<?php echo $this->__('New Ticket') ?>"
            class="button"
        onclick="window.location='<?php echo $this->getAddTicketUrl(); ?>';">
        <span>
            <span>
                <?php echo $this->__('New Ticket') ?>
            </span>
        </span>
    </button>
    <button type="button" title="<?php echo $this->__('Back') ?>"
            class="button"
            onclick="window.location='<?php echo $this->getListTicketsUrl(); ?>';">
        <span>
            <span>
                <?php echo $this->__('Back') ?>
            </span>
        </span>
    </button>
</div>

<div class="customer-list">
    <?php if(!$_collection->count()): ?>
    <h2><?php echo $this->__('You have no archived tickets.') ?></h2>
    </a>
    <?php else: ?>
        <table class="data-table" id="tickets_table" >
            <thead>
                <tr class="first last">
                    <th>Ticket #</th>
                    <th>Subject</th>
                    <th><span class="nobr">Status</span></th>
                    <th><span class="nobr">Created</span></th>
                    <th><span class="nobr"></span></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($_collection as $ticket): ?>
                    <tr>
                        <td>
                            <?php echo $this->escapeHtml($ticket->getTicketId()); ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($ticket->getSubject()); ?>
                        </td>
                        <td>
                            <?php if ($ticket->getStatus() == 0): ?>
                                Closed
                            <?php else: ?>
                                Open
                            <?php endif ?>
                        </td>
                        <td>
                            <?php echo date('j. n. Y. H:i', strtotime($ticket->getCreatedAt())); ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->getUrl('tickets/support/view', array('_query' => array('ticket_id' => $this->escapeHtml($ticket->getTicketId()), 'archive'=> true))) ?>">
                                <?php echo $this->__('View') ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>
