<?php
    $_collection = $this->getTickets();
    $helper = Mage::helper('inchoo_supportticket')
?>
<div class="page-title title-buttons">
    <h1>
        <?php echo $this->__('My Tickets') ?>
    </h1>
    <button type="button" title="<?php echo $this->__('New Ticket') ?>"
            class="button"
        onclick="window.location='<?php echo $this->getAddTicketUrl(); ?>';">
        <span>
            <span>
                <?php echo $this->__('New Ticket') ?>
            </span>
        </span>
    </button>
    <button type="button" title="<?php echo $this->__('All tickets') ?>"
            class="button"
            onclick="window.location='<?php echo $this->getListTicketsUrl(); ?>';">
        <span>
            <span>
                <?php echo $this->__('All tickets') ?>
            </span>
        </span>
    </button>

</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_collection->count()): ?>
<table class="data-table" id="my-tickets-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Ticket #') ?></th>
            <th><?php echo $this->__('Subject') ?></th>
            <th><?php echo $this->__('Status') ?></th>
            <th><?php echo $this->__('') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach($_collection as $ticket): ?>
        <tr>
            <td><?php echo $this->escapeHtml($ticket->getTicketId()); ?></td>
            <td><span class="nobr"><?php echo $this->escapeHtml($ticket->getSubject()); ?></span></td>
            <td>
                <?php if ($this->escapeHtml($ticket->getStatus() == 0)): ?>
                    Closed
                <?php else: ?>
                    Open
                <?php endif ?>
            </td>
            <td>
                <a href="<?php echo $this->getUrl('tickets/support/view', array('ticket_id' => $this->escapeHtml($ticket->getTicketId()), 'archive'=> true)) ?>">
                <?php echo $this->__('View') ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('No archived tickets.'); ?></p>
<?php endif ?>

