<?php
    $ticket = Mage::registry('loaded_ticket');
    $comments = $this->getTicketComments($ticket->getTicketId());
?>
<div class="page-title title-buttons">
    <h1>
        <?php echo $this->__('My Tickets') ?>
    </h1>
    <button type="button" title="<?php echo $this->__('Back to ticket list') ?>"
            class="button"
        onclick="window.location='<?php echo $this->getListTicketsUrl(); ?>';">
        <span>
            <span>
                <?php echo $this->__('Back to ticket list') ?>
            </span>
        </span>
    </button>
</div>
<?php if($ticket->getData('ticket_id')): ?>
    <h3><?php echo $ticket->getSubject(); ?></h3>
    <p><strong><?php echo $this->__('Content:') ?><br> <?php echo $ticket->getContent(); ?></strong></p>
    <div>
    <div>
        <hr>
        <h4>Comments</h4>
        <hr>
        <ul>
        <?php foreach($comments as $comment): ?>
            <li>
                <b>
                    <?php echo $comment->getContent(); ?>
                </b>
                <br>
                <?php echo $comment->getAuthor(); ?>
                <hr>
            </li>
        <?php endforeach ?>
        </ul>
    </div>
    </div>

    <form action="<?php echo $this->getUrl('tickets/support/newComment/')?>" method="post" id="form-validate">
        <fieldset>
            <?php echo $this->getBlockHtml('formkey')?>
            <input type="hidden" name="ticket_id" value="<?php echo $ticket->getTicketId(); ?>">
            <ul class="form-list">
                <li>
                    <label for="ticket_comment_content"><?php echo $this->__('Comment') ?></label>
                    <br>
                    <textarea class="required-entry" name="ticket_comment_content" rows="4" cols="100"></textarea>
                </li>
            </ul>
            <div class="buttons-set">
                <button type="submit" title="Add comment" class="button">
                    <span>
                        <span><?php echo $this->__('Add comment') ?></span>
                    </span>
                </button>
            </div>
        </fieldset>
    </form>
<?php else: ?>
    <h3>This ticket does not exist</h3>
<?endif; ?>

<script type="text/javascript">
//<![CDATA[
var dataForm = new VarienForm('form-validate', true);
//]]>
</script>